### ISSUE TITLE
Create the skeleton of the React application

### ISSUE THREAD

**Issue by GPortas** [IQSS/dataverse-frontend#1]
## Overview of the Feature Request

Even though this issue is created without having established the full scope of the SPA MVP first milestone beforehand, we already know that we need this first issue to establish the skeleton of the React application.

The goal is to create a primitive React SPA, empty in terms of Dataverse features, with a simple "Hello Dataverse" message. This will initialize the codebase for this project, which we will evolve in subsequent issues.

## What kind of user is the feature intended for?
Dataverse frontend developers

## What inspired the request?
- Current work on SPA MVP Strategy
- MVP Strategy document: [link](https://docs.google.com/document/d/1vOSsIGGCbgal4f_lSp1yInQifBcmo5vZ-Z9pfkVDyG4)

## What existing behavior do you want changed?
N/A

## Any brand new behavior do you want to add to Dataverse Frontend?
React application setup with "Hello Dataverse" message

## Any related open or closed issues to this feature request?

- https://github.com/IQSS/dataverse/issues/9347

**Comment by mreekie** [comment]
Grooming:
- Added NIH deliverable label.
