### ISSUE TITLE
[Spike - Frontend] [0/2] Create the File Tab of the Dataset - Analysis

### ISSUE THREAD

**Issue by MellyGray** [IQSS/dataverse-frontend#107]
## Overview of the Feature Request

This is Part 0 of  #94 

Evaluate creating the Files table from scratch or using a third party library for the Dynamic Table Component. The solution we choose must fulfil the following requirements

1. Checkboxes to select multiple rows
2. Accessibility
3. Filters
4. Sorting
5. Search input
6. Possibility of adding different actions to the items, such as a Download button

## What kind of user is the feature intended for?

Developers

## What inspired the request?

- [UI feature development process](https://docs.google.com/document/d/1vOSsIGGCbgal4f_lSp1yInQifBcmo5vZ-Z9pfkVDyG4/edit#heading=h.e6y69fx5m61r)

## What existing behavior do you want changed?

None

## Any brand new behavior do you want to add to Dataverse?

None

## Any open or closed issues related to this feature request?

- #94

**Comment by MellyGray** [comment]
This is the File Table Analysis doc

https://docs.google.com/document/d/1k-HUOuuk0-s9I6BK3rYYdsY_aFEHUV4ExCabXdDtYQw/edit#heading=h.gaj9pza08jcy

**Comment by GPortas** [comment]
The analysis looks good to me. Also, I agree with the library chosen (Lightweight, scalable in terms of performance and highly customizable).
