### ISSUE TITLE
Review architecture related content in the SPA Strategy document and move it to the Architecture document if necessary

### ISSUE THREAD

**Issue by GPortas** [IQSS/dataverse-frontend#108]
## Overview of the Feature Request

The goal is that the SPA MVP strategy document reflects only the strategy and planning of the project, moving any important concept related to architecture to the general architecture document.

Add a summary in "Implementation details" about the current status of the SPA MVP (what we have already done).

## What inspired the request?
- Dataverse monthly meeting

## What kind of user is the feature intended for?
Re-architecture documents readers

## What existing behavior do you want changed?
N/A

## Any brand new behavior do you want to add to Dataverse?
N/A

## Any open or closed issues related to this feature request?
N/A

**Comment by GPortas** [comment]
FYI @rtreacy @siacus 

I have finally decided not to move anything to the architecture or modularity docs. As expected, the concepts that were explained in the MVP strategy document were too specific for those documents.

Instead, to simplify the strategy document as we discussed, I moved the entire MVP description with its functional and non-functional aspects to another document. I considered important to keep this information somewhere and make it accessible to anyone who is interested. This document, called MVP Definition, is referenced from the new strategy document.

I've also implemented a new way to present and track issues in the strategy document, in a more visual and scalable way through a Google Docs table feature.

These are the new documents with links:

- Dataverse - SPA MVP Strategy https://docs.google.com/document/d/1Z1jkcL-42BTiFzrFV2XkSWLUuCq80xfCToX3xLRcIK4
- Dataverse - SPA MVP Definition https://docs.google.com/document/d/1WnJzLeVK5eVP4_10eX6BwPAnmiamO1n2uGzcwrAsucQ

**Comment by rtreacy** [comment]
I have replaced the link in the text in the main document  to the SPA MVP Strategy with the link to SPA MVP Strategy V2 and provided both links in the Reference section of the main doc

**Comment by rtreacy** [comment]
@GPortas @siacus I have replaced the link in the text in the main document to the SPA MVP Strategy with the link to SPA MVP Strategy V2 and provided both links in the Reference section of the main doc

**Comment by cmbz** [comment]
2023/12/15: @rtreacy and @GPortas just following up here. Noticed that issue was moved to Done, however it's still open. Should it be closed?

**Comment by rtreacy** [comment]
yes. closed it
