### ISSUE TITLE
Prepare community day talk: Demo of the MVP for the new Dataverse Single Page Application

### ISSUE THREAD

**Issue by GPortas** [IQSS/dataverse-frontend#111]
## Overview of the Feature Request

Create and prepare the resources necessary for the community talk: Demo of the MVP for the new Dataverse Single Page Application

## What inspired the request?
- Dataverse community day

## What kind of user is the feature intended for?
- Dataverse community day attendees

## What existing behavior do you want changed?
N/A

## Any brand new behavior do you want to add to Dataverse?
N/A

## Any open or closed issues related to this feature request?
N/A

**Comment by cmbz** [comment]
Guillermo will coordinate a meeting with the contributors to discuss and finalize the demo components and strategy.
