### ISSUE TITLE
[Spike - Frontend] UI of the Dataset page action buttons

### ISSUE THREAD

**Issue by GPortas** [IQSS/dataverse-frontend#129]
## Overview of the Feature Request

Spike issue of the UI work for #128.

The goal is to develop just the UI logic, without any behavior that requires data access.

### Mockup of the requested element

![dataset_actionbuttons_1](https://github.com/IQSS/dataverse-frontend/assets/17010447/b676fa7b-77fa-48d4-994d-8f7b5b342d1d)

<img width="316" alt="dataset_actionbuttons_2" src="https://github.com/IQSS/dataverse-frontend/assets/17010447/e0aafecf-1343-4152-a4e8-9a772579e4ef">

## What inspired the request?

- #128 

## What existing behavior do you want changed?

N/A

## Any brand new behavior do you want to add to Dataverse?

N/A

## Any open or closed issues related to this feature request?

- #128

**Comment by MellyGray** [comment]
I added the Waiting label because I need some changes from another PR to be merged into develop, in specific this PR:
- https://github.com/IQSS/dataverse-frontend/pull/165
