### ISSUE TITLE
Set up a beta testing environment

### ISSUE THREAD

**Issue by GPortas** [IQSS/dataverse-frontend#132]
## Overview of the Feature Request
Set up a remote beta testing environment for deploying the latest changes of the SPA in develop branch.

Similarly to the remote QA environment, we will need to configure a remote instance dedicated to this beta testing environment, which will include a Dataverse instance running with the latest API changes for supporting the SPA, and the session auth feature flag enabled.

In addition, we need to establish an automated mechanism that updates the environment automatically (both the SPA and the Dataverse application), to ensure that we always offer the latest changes.

Edit (After 27th weekly meeting):

- Record a demo once we establish the beta testing environment.

Edit. Demo is recorded!

https://drive.google.com/file/d/1T31O6VPsA2rmVeAVlt13W528xrgjJ9vj/view?usp=drive_link

## What kind of user is the feature intended for?
Beta testing users

## What inspired the request
Frontend weekly meeting discussion

## What existing behavior do you want changed?
None

## Any brand new behavior do you want to add to Dataverse?
None

## Any open or closed issues related to this feature request?
Spikes:
- https://github.com/IQSS/dataverse-frontend/issues/153
- https://github.com/IQSS/dataverse/issues/9746

**Comment by donsizemore** [comment]
@GPortas and I are repurposing http://ec2-3-210-184-82.compute-1.amazonaws.com/ as the beta testing environment.

@pdurbin can you do DNS registration for Harvard still? May we have an A record for spa-testing.dataverse.org -> 3.210.184.82? If there's another name you prefer, by all means. I have the key and certs for star.dataverse.org. Thanks.

**Comment by donsizemore** [comment]
We now have certs (and an SSL redirect): https://beta.dataverse.org/ and https://beta.dataverse.org/spa/

**Comment by pdurbin** [comment]
@GPortas I just watched it and it's really good! Can I put it on [DataverseTV](https://github.com/IQSS/dataverse-tv)?!?

**Comment by GPortas** [comment]
@pdurbin Sure! Thank you!

**Comment by pdurbin** [comment]
@GPortas done! Please check out https://iqss.github.io/dataverse-tv/ or https://dataverse.org/dataversetv which should look like this:

![Screen Shot 2023-08-03 at 1 59 26 PM](https://github.com/IQSS/dataverse-frontend/assets/21006/803b116c-b05a-452b-9c9c-bc6956128cde)

If you or others want to rewrite the text, that's fine! It's in this spreadsheet: https://docs.google.com/spreadsheets/d/1uVk_57Ek_A49sLZ5OKdI6QASKloWNzykni3kcYNzpxA/edit?usp=sharing

@dliburd what do you think. Should we upload this video to https://www.youtube.com/@iqssatharvarduniversity8672/videos ? For now I just linked to the mp4 on Google Drive. One nice thing about having the video on YouTube is that DataverseTV shows the thumbnail.

**Comment by dliburd** [comment]
I think we should post this to the Dataverse YouTube page. @sbarbosadataverse Do you agree?

**Comment by pdurbin** [comment]
I announced the video at https://groups.google.com/g/dataverse-community/c/cxZ3Bal_-uo/m/h3kh3iVNCwAJ

I'm happy to follow up on that thread with a YouTube link if it gets uploaded.

@GPortas is there anything else for this issue? Should we close it?

**Comment by GPortas** [comment]
I think we can close it. Thanks @pdurbin.

**Comment by pdurbin** [comment]
Actually, before closing it. What if we add a link to the README? I created a PR for this:

- #155
