### ISSUE TITLE
clarify in README which tags to use with run-env.sh

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse-frontend#177]

**Comment by poikilotherm** [comment]
Might be a good idea to use a default value, too

**Comment by pdurbin** [comment]
Right but not develop if we're pulling from ghcr.io, right? I'm not sure what a sane default for ghcr.io would be. I think it's a bunch of random tags/branches.

**Comment by pdurbin** [comment]
I'd say this was fixed by the following PR:

- #527

Closing.
