### ISSUE TITLE
[Spike - Frontend] Analyze downloading options of the Dataset page in view mode and create spike issues

### ISSUE THREAD

**Issue by GPortas** [IQSS/dataverse-frontend#182]
## Overview of the Feature Request

The goal of this issue is to analyze the required frontend development for #63 and create spike issues (UI ).

## What inspired the request?

- https://github.com/IQSS/dataverse-frontend/issues/63

## Any open or closed issues related to this feature request?

- https://github.com/IQSS/dataverse-frontend/issues/63
- https://github.com/IQSS/dataverse-frontend/issues/191

**Comment by MellyGray** [comment]
- [Frontend] Cite Dataset-> Size: 10

![Captura de pantalla 2023-10-02 a las 11 09 45](https://github.com/IQSS/dataverse-frontend/assets/23359572/30d261bd-5496-4258-b2f0-4f70e8fc16ec)

- [Frontend] Access File Download Options -> Size: 80
![Captura de pantalla 2023-10-02 a las 11 11 42](https://github.com/IQSS/dataverse-frontend/assets/23359572/cadd6b1a-0ea6-462f-9405-381e8d331417)
 
- [Frontend] Files Table Header Download Button -> Size: 10
![Captura de pantalla 2023-10-02 a las 11 11 10](https://github.com/IQSS/dataverse-frontend/assets/23359572/ae7bd489-fb6e-45e4-b78f-bd7853925b2b)

- [Frontend] Access Dataset Download Button -> Size 33
![Captura de pantalla 2023-10-02 a las 11 10 44](https://github.com/IQSS/dataverse-frontend/assets/23359572/6f89718a-2e6f-4f20-8b9e-547f4ee0fe41)

- [Frontend] Export Metadata Button -> Size 10
![Captura de pantalla 2023-10-02 a las 11 14 41](https://github.com/IQSS/dataverse-frontend/assets/23359572/4a4ad652-a758-4cea-9ccc-10e9616f884c)

**Comment by sekmiller** [comment]
There are some additional ui options when there are tabular files present in the dataset. I have noted them in the sub-issues created in the spike
