### ISSUE TITLE
[Frontend] Files Table Download Button

### ISSUE THREAD

**Issue by MellyGray** [IQSS/dataverse-frontend#187]
## Overview of the Feature Request

The goal is to add the Download Button to the Files Table in the Dataset Page view mode. This include the functionality of selecting different files from the table and downloading the selection.

### Mockup of the requested element
![Captura de pantalla 2023-10-02 a las 11 11 10](https://github.com/IQSS/dataverse-frontend/assets/23359572/ae7bd489-fb6e-45e4-b78f-bd7853925b2b)

### For tabular data this is a dropdown
![Screen Shot 2023-10-05 at 2 49 22 PM](https://github.com/IQSS/dataverse-frontend/assets/2364928/4070a37d-f489-4af1-a2e0-da49976b3aea)

## What inspired the request?

- #63 

## What existing behavior do you want changed?

None

## Any brand new behavior do you want to add to Dataverse?

- Add the Download Button to the Files Table in the Dataset Page view mode

## Any open or closed issues related to this feature request?

- #63
- #182

**Comment by sekmiller** [comment]
![Screen Shot 2023-10-05 at 2 49 22 PM](https://github.com/IQSS/dataverse-frontend/assets/2364928/4070a37d-f489-4af1-a2e0-da49976b3aea)

This will have a dropdown menu if there are tabular files present
