### ISSUE TITLE
Add Dataset Download Options

### ISSUE THREAD

**Issue by MellyGray** [IQSS/dataverse-frontend#188]
## Overview of the Feature Request

The goal is to add the Dataset Download Options to the existing Access Dataset Dropdown in the Dataset Page view mode.

### Mockup of the requested element
![Captura de pantalla 2023-10-02 a las 11 10 44](https://github.com/IQSS/dataverse-frontend/assets/23359572/6f89718a-2e6f-4f20-8b9e-547f4ee0fe41)

### For tabular files
![Screen Shot 2023-10-05 at 2 45 49 PM](https://github.com/IQSS/dataverse-frontend/assets/2364928/945719d0-4329-4acd-8cf3-22dc78bf38ec)

## What inspired the request?

- #63 

## What existing behavior do you want changed?

None

## Any brand new behavior do you want to add to Dataverse?

- Add the Dataset Download Options to the existing Access Dataset Dropdown

## Any open or closed issues related to this feature request?

- #63
- #182

**Comment by sekmiller** [comment]
![Screen Shot 2023-10-05 at 2 45 49 PM](https://github.com/IQSS/dataverse-frontend/assets/2364928/945719d0-4329-4acd-8cf3-22dc78bf38ec)

This may be different if there are tabular files present
