### ISSUE TITLE
Files Table row selection Download Button

### ISSUE THREAD

**Issue by MellyGray** [IQSS/dataverse-frontend#221]
## Overview of the Feature Request
Integrate the Download button from the Files Table to actually download the selected files.

## What kind of user is the feature intended for?
All of them

## What inspired the request?
- https://github.com/IQSS/dataverse-frontend/issues/187

## What existing behavior do you want changed?
None

## Any brand new behavior do you want to add to Dataverse?
Be able to download the selected files using the Download button in the Files Table

## Any open or closed issues related to this feature request?
- https://github.com/IQSS/dataverse-frontend/issues/187

**Comment by GPortas** [comment]
For multiple file download, we can use the existing /access/datafiles endpoint: [API Guide](https://guides.dataverse.org/en/latest/api/dataaccess.html#multiple-file-bundle-download). This endpoint provides the option to download original or archival files.
