### ISSUE TITLE
Record a second demo video of the SPA showing the latest features

### ISSUE THREAD

**Issue by GPortas** [IQSS/dataverse-frontend#239]
## Overview of the Feature Request

Record a second demo video of the SPA showing the latest features.

## What kind of user is the feature intended for?
SPA users.

## What inspired the request?
- Latest migrated features. 
 
## What existing behavior do you want changed?
N/A

## Any brand new behavior do you want to add to Dataverse?
N/A

## Any open or closed issues related to this feature request?
- None

**Comment by MellyGray** [comment]
Here is the video:
https://drive.google.com/file/d/1uo3wJM4wlLpPouGM4zbxCAy2pCIjXfFn/view?usp=sharing

**Comment by GPortas** [comment]
The video is awesome!! Very well explained! 👏👏👏

@pdurbin Do you think we can share it with the community? Once shared, I think we can close this issue.

**Comment by pdurbin** [comment]
Sure, last time I

- put the video on DataverseTV: https://dataverse.org/dataversetv
- made this small writeup: https://groups.google.com/g/dataverse-community/c/cxZ3Bal_-uo/m/h3kh3iVNCwAJ
- mentioned it in the community news: https://groups.google.com/g/dataverse-community/c/s0px7zY-7Q4/m/fSDPs2SaAwAJ

I could do this again. Or someone else could (please just let me know).

**Comment by pdurbin** [comment]
Ok, I did all of the above. The community news is still a [draft](https://docs.google.com/document/d/1X0nDwCZMOkbDpgrTvFS4oNxsAc9IUvNUsvg68W22h48/edit?usp=sharing). I [posted](https://groups.google.com/g/dataverse-community/c/w_rEMddESYc/m/6F7QC1p-AgAJ) to the google group, updated DataverseTV (screenshot below) and opened this PR:

- #267 

![Screenshot 2023-12-15 at 9 38 01 AM](https://github.com/IQSS/dataverse-frontend/assets/21006/5c7034a9-612c-4c3d-8bea-43b09781e0aa)

The PR closes this issue so (as is our custom), I'll remove this issue from the (new!) board.
