### ISSUE TITLE
[Docs] Dataverse Frontend Guide

### ISSUE THREAD

**Issue by GPortas** [IQSS/dataverse-frontend#26]
## Overview of the Feature Request
Goal: Set up the documentation guides for the Dataverse Frontend project, similar to the general sphinx-based Dataverse guides, but specific to the Frontend application.

- Documentation will be hosted on Git as a README or series of README files as needed.

A part from the general project documentation, there are some specific TODO's (to document) from PR discussions that need to be addressed:

- [x]  Explain Object Mother pattern in the documentation and link Martin Fowler article as discussed in this PR:   https://github.com/IQSS/dataverse-frontend/pull/260#discussion_r1451605405

## What kind of user is the feature intended for?
- Dataverse users and frontend developers

## What inspired the request?
- Recent needs to document frontend procedures. For example: application deployment and accessibility changes. We are currently documenting these procedures in the project README, though they will eventually be migrated to the guides once they are established.
- Discussion with @pdurbin 
- #16

## What existing behavior do you want changed?
N/A

## Any brand new behavior do you want to add to Dataverse Frontend?
N/A

## Any related open or closed issues to this feature request?
- #16

**Comment by pdurbin** [comment]
> We don't necessarily have to use sphinx for these guides. Let's do research on possible implementations to find the best fit.

There's active discussion about Sphinx vs. other options for a relaunched version of https://dataversecommunity.global (which is currently an OpenScholar/Drupal site but might become a static site at https://github.com/gdcc/dataversecommunity.global ):

https://dataverse.zulipchat.com/#narrow/stream/375707-community/topic/migrate.20GDCC.20github.20pages

To summarize the tools mentioned so far:

- Sphinx
- Sphinx with Markdown using MyST: https://myst-parser.readthedocs.io
- Jekyll
- mkdocs: https://squidfunk.github.io/mkdocs-material/getting-started/
- Docusaurus (see https://github.com/IQSS/dataverse/issues/8905 )

**Comment by pdurbin** [comment]
In tech hours yesterday I briefly presented the "Sphinx with Markdown using MyST" option in the context of fixing https://dataversecommunity.global by switching it from OpenScholar (where everything but the homepage is [broken](https://dataversecommunity.global/about)) to something, anything on GitHub Pages. Here's the code so far: https://github.com/gdcc/dataversecommunity.global/tree/sphinx-markdown

I thought @ekraffmiller made a good point: is the README enough for now? It makes me question if this should be in "sprint ready" or not. 🤔 

Anyway, @GPortas and @MellyGray weren't there so maybe we should catch up with them before picking up this issue.

**Comment by pdurbin** [comment]
We talked about this during sprint planning. @scolapasta @GPortas and I agree with @ekraffmiller 's idea of continuing with the README for now. We're de-prioritizing this, removing it from sprint ready.

**Comment by cmbz** [comment]
2023/12/14: Assigned to @M27Mangan and added to Sprint Ready as per conversation with @siacus

**Comment by pdurbin** [comment]
From a discussion [in Slack](https://iqss.slack.com/archives/CVB2SMDFX/p1706012021687049?thread_ts=1705950610.714249&cid=CVB2SMDFX), it might be nice to add a badge to the README that says something like "accessibility tests passing". Here's how the badges look now:

![Screenshot 2024-01-23 at 7 11 52 AM](https://github.com/IQSS/dataverse-frontend/assets/21006/2bf91f05-607e-4588-8c90-d7af2de6a6ea)

From @MellyGray:

"We’re using the Storybook addon for accessibility (https://storybook.js.org/addons/@storybook/addon-a11y), which doesn’t give a single “score”but rather reports on individual accessibility violations or issues found in the stories Therefore, I think we can’t create a badge to display an overall accessibility score, but we can add a badge to indicate whether the accessibility tests are passing, like the “tests passing” badge but for the accessibility tests"

**Comment by jaysundu** [comment]
This seems like a splendid idea to me. I like how it raises the visibility and importance of accessibility testing.

**Comment by M27Mangan** [comment]
Opened https://github.com/IQSS/dataverse-frontend/tree/docs/26-add-frontend-guides
