### ISSUE TITLE
'Loading' text briefly appears when navigating from Home Page to View Dataset Page

### ISSUE THREAD

**Issue by ekraffmiller** [IQSS/dataverse-frontend#279]
From Guillermo's QA comments, steps to reproduce:

I have done different tests, which I share below with videos and the steps to reproduce.

I'm using emojis (🚨 and ✅) to explain if the behavior is working as expected or if revision is required.

**TEST 1 - Create first dataset from empty installation**

https://github.com/IQSS/dataverse-frontend/assets/17010447/60c11a1e-6ad3-4827-861c-1655a5ebb651

Steps:

1. Dataverse is empty, so I log in via JSF to create a data set.
2. I create a test dataset through JSF
3. I navigate to the JSF home page to see how the created dataset card is displayed in the list.
4. ✅ I navigate to the SPA home page to verify that the new dataset is displayed in the list with the same appearance as in JSF.
5. 🚨 I click the dataset in the list and navigate to the dataset page. I see that when navigating, instead of directly opening the dataset page, it goes through an intermediate page where a text "loading" appears (very quickly, but noticeable). See the following screenshot:

<img width="408" alt="LOADINGPAGE" src="https://github.com/IQSS/dataverse-frontend/assets/17010447/46cb8c29-144e-43a1-b62f-6409e063e527">

6. ✅ The dataset page correctly displays the requested dataset

_Originally posted by @GPortas in https://github.com/IQSS/dataverse-frontend/pull/274#pullrequestreview-1813474292_

**Comment by M27Mangan** [comment]
I think the loading functionality should appear lower in the component hierarchy, possibly including a skeleton component. In my opinion there should be some visual communication to the user that there is data being fetched and the website is actively working. Attempting to recreate every aspect of the JSF site (including the not ideal ones) would be counterproductive I think. Happy to take this item and work with stakeholders.
