### ISSUE TITLE
Create a npm module for the Dataverse Design System so the community can use it for their applications and future plugins

### ISSUE THREAD

**Issue by GPortas** [IQSS/dataverse-frontend#28]
## Overview of the Feature Request

The goal is to create a npm module that includes the elements of the Dataverse Design System, decoupled from the frontend application. The initial elements to be included in this plugin will be identified in #14.

This npm module will have an associated GitHub repository, as well as independent versioning. The module will be installed on the Dataverse Frontend application, as well as any other application of the community which needs to use the Dataverse UI elements. The future Dataverse plugins, as described in #23, will be able to use this module as well.

We will develop the UI elements identified in #14 directly on this module.

## What kind of user is the feature intended for?
Dataverse frontend developers

## What inspired the request?
- Frontend subgroup weekly meeting
- #23 

## What existing behavior do you want changed?
N/A

## Any brand new behavior do you want to add to Dataverse Frontend?
N/A

## Any related open or closed issues to this feature request?
- #14 
- #23 
- #39

**Comment by pdurbin** [comment]
If it helps, in the Storybook 7 [launch video](https://www.youtube.com/watch?v=P0hJm5v8TJw), Monday.com talked about their open source UI library called Vibe ( https://github.com/mondaycom/monday-ui-react-core ). Perhaps we can draw inspiration from it.

**Comment by johannes-darms** [comment]
We are also using storybook to develop isolated components https://github.com/nfdi4health/semlookp-widgets and its works quite well.
