### ISSUE TITLE
Use Query Param in Home Page dataset list pagination

### ISSUE THREAD

**Issue by ekraffmiller** [IQSS/dataverse-frontend#280]
From Guillermo' QA comments, steps to reproduce:

**TEST 4 - Pagination: Back button and URL page query param**

🚨

In JSF, a query parameter is added to the URL to indicate the results page you are on. I think we should continue to support this. It is useful for scenarios like the following:

- When you have navigated to a new result page, by clicking on the browser's back button you navigate to the previously selected page.

- With the query param you are also able to share a URL that leads directly to a particular page on the home page.

You can see in the following video how, by not adding the query parameter, the back button navigates to the page before reaching the home page.

https://github.com/IQSS/dataverse-frontend/assets/17010447/618710aa-a48d-4472-9e57-8cd76ab49c71

_Originally posted by @GPortas in https://github.com/IQSS/dataverse-frontend/pull/274#pullrequestreview-1813474292_

**Comment by pdurbin** [comment]
I'm glad I didn't have to ask for continued support for this. 😄  On the JSF side I made sure the query parameters are present in the URL so people can bookmark or send links around or even hack on the URL. I think they're useful.

JSF has a limitation where you can't have the same parameter over and over. However, in the Search API we repeat `fq` as often as we like. I imagine the SPA would work like the Search API.
