### ISSUE TITLE
[Analysis] Add all required fields to the Create Dataset Form

### ISSUE THREAD

**Issue by GPortas** [IQSS/dataverse-frontend#282]
## Overview of the Feature Request

This issue is an analysis for #252 

Within the scope we seek to understand how to dynamically compose the form of a metadata block by consulting js-dataverse.

This issue does not require code implementation, just an analysis for a future implementation.

## What kind of user is the feature intended for?
All of them

## What inspired the request?
- https://github.com/IQSS/dataverse-frontend/issues/252

## What existing behavior do you want changed?
None

## Any brand new behavior do you want to add to Dataverse?
None

## Any open or closed issues related to this feature request?
- https://github.com/IQSS/dataverse-frontend/issues/252

**Comment by MellyGray** [comment]
Closing this issue because we've consider that we can perform the analysis at the same time in this new issue scope

- #336
