### ISSUE TITLE
Complete UI Working Group Landing Page

### ISSUE THREAD

**Issue by ekraffmiller** [IQSS/dataverse-frontend#288]
For the Community Meeting, we want to complete and publish the UI Working Group landing page.
I created an issue in the repository for this page: https://github.com/gdcc/ui.gdcc.io/issues/1

**Comment by ekraffmiller** [comment]
Notes for Reviewer: I didn't create a PR for this issue, but the website can be reviewed here: https://ui.gdcc.io/.   Any suggested changes/improvements to the site are welcome.  If there is a lot to change, maybe we can create an issue in the website repository, otherwise it can be discussed here.

**Comment by pdurbin** [comment]
Looks good to me! I think my only suggestion to pick either "frontend" or "front end" and stick with it.

**Comment by pdurbin** [comment]
Looks good now! Closing.

**Comment by pdurbin** [comment]
@ekraffmiller et al., one last thing, I just created a pull request to update the list of working/interest groups:

- https://github.com/gdcc/dataversecommunity.global/pull/3
