### ISSUE TITLE
Display real dataset version information in the File Page

### ISSUE THREAD

**Issue by MellyGray** [IQSS/dataverse-frontend#295]
## Overview of the Feature Request
The js-dataverse module GetFile use case it's going to be extended to retrieve the dataset version information needed to display it in the File Page. We need to integrate the module changes with the SPA. Currently we're using mock data for the dataset version information so it would be just replacing this mock data by the real dataset version information retrieved by the module.

This issues depends on:
https://github.com/IQSS/dataverse-client-javascript/issues/123

## What kind of user is the feature intended for?
All of them

## What inspired the request?
- https://github.com/IQSS/dataverse-client-javascript/issues/123

## What existing behavior do you want changed?
None

## Any brand new behavior do you want to add to Dataverse?
Display real dataset version information in the File Page

## Any open or closed issues related to this feature request?
- https://github.com/IQSS/dataverse-frontend/issues/283

**Comment by GPortas** [comment]
Removing waiting label as we already have a dev docker image with the required API extension from: https://github.com/IQSS/dataverse/pull/10299

This is the image tag: `ghcr.io/gdcc/dataverse:10280-get-file-api-extension`
