### ISSUE TITLE
Storybook setup

### ISSUE THREAD

**Issue by GPortas** [IQSS/dataverse-frontend#3]
## Overview of the Feature Request

[Storybook](https://storybook.js.org/) is an open source frontend tool for building UI components and pages in isolation. This tool has many useful features that we can use for the SPA development, such as enhanced testability, easy components reutilization, documentation, etc.

The goal of this issue is to setup Storybook in the project and prepare it for the development of upcoming frontend features.

## What kind of user is the feature intended for?
Dataverse frontend developers and QA

## What inspired the request?
- Current work on SPA MVP Strategy
- MVP Strategy document: [link](https://docs.google.com/document/d/1vOSsIGGCbgal4f_lSp1yInQifBcmo5vZ-Z9pfkVDyG4)

## What existing behavior do you want changed?
N/A

## Any brand new behavior do you want to add to Dataverse Frontend?
Storybook setup

## Any related open or closed issues to this feature request?

- https://github.com/IQSS/dataverse-frontend/issues/2

**Comment by mreekie** [comment]
Grooming:
- Added NIH deliverable label.
