### ISSUE TITLE
Create the design tokens of the design system using SASS variables

### ISSUE THREAD

**Issue by MellyGray** [IQSS/dataverse-frontend#30]
## Overview of the Feature Request

We would like to add the design tokens of our design system to Storybook and to the code using SASS variables to make it easier for developers to reference and use these tokens in their projects. These design tokens are specified in the [Design System analysis document](https://docs.google.com/document/d/1OxCQO7B-yJaMWRl8EzuflcSmIaCmVSs19aoD83PjPmA/edit#heading=h.pjqhiu86e7l8).

## What kind of user is the feature intended for?

This feature is intended for developers who use Storybook to build and test components for our web application.

## What inspired the request?

Our design system includes a set of design tokens that define our brand colors, typography, spacing, and other styles. These tokens are used consistently across our applications to ensure a cohesive and polished user experience. However, developers currently have to manually reference these tokens in their code, which can be time-consuming and error-prone. By adding the design tokens with SASS variables and document them in the Storybook, we can provide a centralized and easy-to-use reference for developers.

Some references for the Storybook:

- [Vibe Design System](https://style.monday.com/?path=/docs/foundations-colors--page)
- [Storybook Design System](https://storybook-design-system.netlify.app/?path=/docs/colors--page)
- [More references](https://storybook.js.org/showcase)

## What existing behavior do you want changed?

We want to add a new section to Storybook that displays our design tokens in a clear and organized way. This section should include documentation on how to use each token, as well as examples of how the tokens can be applied to different components. This tokens would be used in the scss files using SASS variables. 

## Any brand new behavior do you want to add to Dataverse?

No, this feature request does not introduce any brand new behavior to Dataverse.

## Any open or closed issues related to this feature request?

- https://github.com/IQSS/dataverse-frontend/issues/14

**Comment by mreekie** [comment]
Grooming:
- Talked with  Melina prior to the kickoff.
- This is one of 3 issues she let me know were already sized and that would be worked in this sprint.
- Moving them to the right columns in the backlog and sprint board.
