### ISSUE TITLE
Add 'Add Data' button to the Home page and navbar

### ISSUE THREAD

**Issue by MellyGray** [IQSS/dataverse-frontend#303]
## Overview of the Feature Request
Add the  'Add Data' button to Home page to redirect to the Create Dataset Form page

Features:

1. Add  'Add Data' button to Home page
2. Add  'Add Data' button to the navbar
3. Link them to the Create Dataset Form page

Since we don't have the Create Dataverse Form ready, we can mark this option of the menu as disabled. Also, notice that the button variant will be the secondary variant.

## Mock
![image](https://github.com/IQSS/dataverse-frontend/assets/23359572/a72e6606-5303-489b-a237-9d8dbb716b0b)
![image](https://github.com/IQSS/dataverse-frontend/assets/23359572/6a3b5c43-38c5-4095-9226-c74e47dfbb7f)

## What kind of user is the feature intended for?
All users

## What inspired the request?
- https://github.com/IQSS/dataverse-frontend/issues/231

## What existing behavior do you want changed?
None

## Any brand new behavior do you want to add to Dataverse?
No

## Any open or closed issues related to this feature request?
- #231

**Comment by M27Mangan** [comment]
Referenced two new issues #318 & #319 in todo's related to the Add Data button
