### ISSUE TITLE
Release design system npm package version 1.2.0

### ISSUE THREAD

**Issue by GPortas** [IQSS/dataverse-frontend#313]
## Overview of the Feature Request

Release version 1.2.0 of the design system to the npm registry.

## What kind of user is the feature intended for?
Design system package consumer

## What inspired the request?
- https://github.com/IQSS/dataverse-client-javascript/issues/123

## What existing behavior do you want changed?
None

**Comment by MellyGray** [comment]
Typescript error here https://github.com/IQSS/js-dataverse-front-end-examples/tree/main/react-design-system-example

![Image](https://github.com/IQSS/dataverse-frontend/assets/23359572/9f5023c4-bc0a-43c2-ac25-20e258e65235)



I think we need to change this from the design system package.json from this
```
"types": "./dist/index.d.ts",
"exports": {
  ".": {
    "import": "./dist/index.es.js",
    "require": "./dist/index.umd.js"
  }
},
```
to this
```
"types": "./dist/index.d.ts",
"exports": {
  ".": {
    "import": "./dist/index.es.js",
    "require": "./dist/index.umd.js"
     "types": "./dist/index.d.ts",
  }
},
```
