### ISSUE TITLE
"New Collection" Page

### ISSUE THREAD

**Issue by M27Mangan** [IQSS/dataverse-frontend#319]
## Overview of the Feature Request
Create "New Collection" page to create a new collection.
Integrate with Create Collection use case from [PR](https://github.com/IQSS/dataverse-client-javascript/pull/155) 

## Features
1. Breadcrumbs
2. Navigation (from New collection button on Add Data dropdowns from both header and collections page)
3. Depending on which collection the user is in when clicking on the New Collection button, the parent collection in which it should be created will be known.
4. Host Dataverse readonly for now.

### Fields to create:

- Host Dataverse (readonly, prefilled) => defaults to root
- Dataverse Name (required)
- Identifier (required)
- Category (required)
- Email (required, can be multiple)
- Affiliation (not required)
- Description (not required)

 _**Metadata Fields**_ and **_Browse/Search Facets_** will be developed in a following iteration.

<img width="600" alt="Screenshot 2024-07-04 at 15 51 19" src="https://github.com/IQSS/dataverse-frontend/assets/64560524/c2f9ea8f-6ac8-4039-970b-fa0356153272">

## Any open or closed issues related to this feature request?
JS-Dataverse [PR](https://github.com/IQSS/dataverse-client-javascript/pull/155)

**Comment by GermanSaracca** [comment]
I have updated the issue description and scope.
