### ISSUE TITLE
Support dynamic scrolling in addition to table view pagination

### ISSUE THREAD

**Issue by GPortas** [IQSS/dataverse-frontend#322]
## Overview of the Feature Request

The goal is to have the option to display the current resource table views (collection files or datasets tab) using dynamic scrolling instead of pages, just as the Google search does.

This topic will require more detailed analysis and will possibly be divided into more than one issue.

## What kind of user is the feature intended for?
SPA user

## What inspired the request?
- Frontend weekly meeting

**Comment by GermanSaracca** [comment]
At the moment, I think an initial approach for this version would be to implement infinite scrolling on the initial listing on the main page.
Part of this decision is based on testing this functionality only in one part of the UI and specifically not in a table.
A configuration `javascript `file will be created to switch from infinite scrolling to common pagination via the pagination controls.  
A second instance of this version could be to add a toggle button to make this switch.

**Comment by cmbz** [comment]
Closed as complete. Additional issues will be opened to address infinite scrolling refinements.
