### ISSUE TITLE
[Spike - Developer Guide] Writing test cases

### ISSUE THREAD

**Issue by GPortas** [IQSS/dataverse-frontend#326]
## Overview of the Feature Request

Create the second section of the developer guide: _Writing test cases_

This issue is a spike created from https://github.com/IQSS/dataverse-frontend/issues/304 to narrow the scope a little and be able to better prioritize it.

## What kind of user is the feature intended for?
Developers.

## What inspired the request?
- https://github.com/IQSS/dataverse-frontend/issues/304

## What existing behavior do you want changed?
N/A

## Any brand new behavior do you want to add to Dataverse?
N/A

## Any open or closed issues related to this feature request?
- https://github.com/IQSS/dataverse-frontend/issues/304

**Comment by g-saracca** [comment]
Closed by https://github.com/IQSS/dataverse-frontend/pull/349
