### ISSUE TITLE
fix docker compose file post #10357 merging

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse-frontend#332]
Merging the following PR...

- https://github.com/IQSS/dataverse/pull/10234

... means we need to update the docker compose file.

Otherwise, you will get this in server.log...

`No PidProviders configured via dataverse.pid.providers. Please consider updating as older PIDProvider configuration mechanisms will be removed in a future version of Dataverse.`

... followed by `jakarta.ejb.EJBException: jakarta.ejb.CreateException: Initialization failed for Singleton ConfigCheckService`

**Comment by ekraffmiller** [comment]
I tried it out and it works great, thanks!
