### ISSUE TITLE
Create new label  “help wanted” or “good first issue"  and explain it in the CONTRIBUTING doc

### ISSUE THREAD

**Issue by GPortas** [IQSS/dataverse-frontend#364]
## Overview of the Feature Request

Create a new label for candidate issues for community contribution and mention it in the CONTRIBUTING doc

## What inspired the request?
- [Q2 plan](https://docs.google.com/document/d/1uE0s-XxL-cLzcXJ3buyrbpc95bqKIewagaOtVAsMPGI/edit)

## What existing behavior do you want changed?
None

## Any brand new behavior do you want to add to Dataverse?
None
## Any open or closed issues related to this feature request?

- https://github.com/IQSS/dataverse-frontend/issues/356

**Comment by ekraffmiller** [comment]
In reading about the use of different labels, 'good first issue' tends be used for new comers to the project, where as 'help wanted' is for issues that community contributors of all levels of experience can help with.  So I decided to add both to our first issue, #356 .

**Comment by ekraffmiller** [comment]
@GPortas since there is no code associated with this, is it ok to close?

**Comment by pdurbin** [comment]
I think the labels you picked and perfect and very standard. They both get created automatically when you create a new repo.

The one thing I would caution us about is that "good first issue" is supposed to be good for newcomers so you might want to reserve it for the easiest issues possible. We could even create some extra-easy issues.

Also I believe the thinking is that after a contributor has tackled a good first issue, they are supposed to move on to other issues (and let newcomers pick up other good first issues). So it's good that we have "help wanted" as well, for the tougher issues.

Just something to think about. Again, these labels seem great!

**Comment by ekraffmiller** [comment]
> > @GPortas since there is no code associated with this, is it ok to close?
> 
> I would describe the new labels in the CONTRIBUTING doc, which would require a PR, what do you think? @ekraffmiller

Sorry I missed your comment earlier, @GPortas.  We have a reference to it in the CONTRIBUTING doc, but there was a typo in one of the links, which I fixed
