### ISSUE TITLE
Describe and link the SPA milestones (Q1,Q2,etc) in the repository docs

### ISSUE THREAD

**Issue by GPortas** [IQSS/dataverse-frontend#378]
**Overview of the Feature Request**

Describe and link the SPA milestones (Q1,Q2,etc) in the repository docs.

**What kind of user is the feature intended for?**
Any user

**What inspired the request?**
Weekly meeting

**What existing behavior do you want changed?**
None

**Any brand-new behavior do you want to add to Dataverse?**
None

**Any open or closed issues related to this feature request?**
None

**Comment by pdurbin** [comment]
Related:

- #235
