### ISSUE TITLE
Record the third demo video to showcase the new SPA features

### ISSUE THREAD

**Issue by GPortas** [IQSS/dataverse-frontend#379]
**Overview of the Feature Request**

Record the third demo video to showcase the new SPA features

**What kind of user is the feature intended for?**
All users

**What inspired the request?**
Frontend dev team post standup meeting

**What existing behavior do you want changed?**
N/A

**Any brand-new behavior do you want to add to Dataverse?**
N/A

**Any open or closed issues related to this feature request?**
N/A

**Comment by cmbz** [comment]
2024/07/31
- Waiting for Q2 PRs to be merged.

**Comment by GPortas** [comment]
Waiting for the file upload feature to be fully integrated in the SPA.

**Comment by GPortas** [comment]
Waiting for https://github.com/IQSS/dataverse-frontend/pull/466 to be merged

**Comment by GPortas** [comment]
https://drive.google.com/file/d/1JCMEMNWEzdpA_URbuEBPGn-nJZk4J-rl/view?usp=sharing

**Comment by pdurbin** [comment]
Great video! I just announced it: https://groups.google.com/g/dataverse-community/c/heSnBRhhriM/m/bFgLDvvZAQAJ
