### ISSUE TITLE
Create a npm module for a Dataverse API client so the frontend application and other community applications can use it

### ISSUE THREAD

**Issue by GPortas** [IQSS/dataverse-frontend#39]
## Overview of the Feature Request

The goal is to create a npm module to include the Dataverse API access logic, decoupled from the frontend application, so it can be reused from other applications and future plugins.

This module is similar to the exiting [js-dataverse module](https://github.com/IQSS/dataverse-client-javascript), but with a more advanced design. In the analysis done in #13, we can find the necessary aspects for the new module. [See the analysis document](https://docs.google.com/document/d/1s_ZPr3BRlCuL5Jch8qJ3odncIgkmo6krSn2tMVv5e44)

This npm module will have an associated GitHub repository, as well as independent versioning. The module will be installed on the Dataverse Frontend application, as well as any other application which needs to use it.

In the scope of this issue, and to cover an initial API endpoint within the module, we'll focus on covering endpoints related to version number retrieval, which is required for #12.

## What kind of user is the feature intended for?
Dataverse frontend developers

## What inspired the request?
- #13 

## What existing behavior do you want changed?
N/A

## Any brand new behavior do you want to add to Dataverse Frontend?
N/A

## Any related open or closed issues to this feature request?
- #13 
- #12  
- #28

**Comment by mreekie** [comment]
Grooming:
- Talked with  Melina prior to the kickoff.
- This is one of 3 issues she let me know were already sized and that would be worked in this sprint.
- Moving them to the right columns in the backlog and sprint board.
