### ISSUE TITLE
Create Dataset: email validation does not match validation in the Dataverse API

### ISSUE THREAD

**Issue by ekraffmiller** [IQSS/dataverse-frontend#393]
**What steps does it take to reproduce the issue?**
Go to Create Dataset form, in Point of Contact email, enter an email address that ends with a non-tld string, for example, 'ellen@test.e' and all the other required fields

- When does this issue occur?
When submitting Create Dataset form
- Which page(s) does it occur on?
Create Dataset
- What happens?
It shows an Alert message about a validation error, but it doesn't say what the error is, and the email field isn't highlighted
<img width="476" alt="Screenshot 2024-05-01 at 3 17 17 PM" src="https://github.com/IQSS/dataverse-frontend/assets/675224/2e213902-0d75-427a-959b-01cdccaf8729">

In the Network tab, the create fails with 403 and this error message:
```
{
    "status": "ERROR",
    "message": "Validation Failed: Point of Contact E-mail ellen@test.e  is not a valid email address. (Invalid value:edu.harvard.iq.dataverse.DatasetFieldValueValue[ id=null ]).java.util.stream.ReferencePipeline$3@626c7975"
}
```

**Comment by pdurbin** [comment]
Just a couple details [from Slack](https://iqss.slack.com/archives/C010LA04BCG/p1714587982819129):

- On the backend we use https://github.com/apache/commons-validator
- Perhaps `.e` is rejected because it isn't a valid TLD according to https://en.wikipedia.org/wiki/List_of_Internet_top-level_domains or http://www.iana.org/domains/root/db

**Comment by GermanSaracca** [comment]
Waiting for [Dynamic Multiple Fields PR](https://github.com/IQSS/dataverse-frontend/pull/395) to be merged.
In the above-mentioned pr, there are some changes and refactor that could be better to wait until keep working on this issue to avoid lots of merging conflicts.
