### ISSUE TITLE
update Github actions so they are triggered from opening a Pull Request

### ISSUE THREAD

**Issue by ekraffmiller** [IQSS/dataverse-frontend#398]
When contributors open a PR, it would be helpful to have all the same tests run that we currently have for pushing commits

**Comment by pdurbin** [comment]
If it helps, @poikilotherm created a detailed diagram about how GitHub Actions are configured with external contributors in mind for the main "dataverse" repo:

![Image](https://github.com/IQSS/dataverse-frontend/assets/21006/e7f2cb12-acf7-4f0c-9b83-a88cd0d76eb7)

The pull request hasn't been merged yet:

- https://github.com/IQSS/dataverse/pull/9776

To see the diagram in context: https://dataverse-guide--9776.org.readthedocs.build/en/9776/container/auto-usage.html
