### ISSUE TITLE
Add mdx template for the Storybook documentation of the design system elements

### ISSUE THREAD

**Issue by MellyGray** [IQSS/dataverse-frontend#40]
## Overview of the Feature Request

To provide the documentation of the design system we will be using the Storybook docs capabilities. Then, we'll need to create a template for the docs in .mdx format. This template is intended to be used with the design system elements, not necessary for the rest of the components of the SPA.

The current style guide could be a reference for this documentation. As well as other public Storybook:

- [Dataverse style guide](https://guides.dataverse.org/en/latest/style/index.html)
- [Storybook design system](https://storybook-design-system.netlify.app/?path=/docs/button--basic)
- [Monday storybook](https://style.monday.com/?path=/docs/buttons-button--overview)

## What kind of user is the feature intended for?
Developers and contributors

## What inspired the request?
The analysis of the Design System elements.

## What existing behavior do you want changed?
None

## Any brand new behavior do you want to add to Dataverse?
Storybook documentation template for the design system elements

## Any open or closed issues related to this feature request?

- https://github.com/IQSS/dataverse-frontend/issues/14

**Comment by mreekie** [comment]
Grooming:
- Talked with  Melina prior to the kickoff.
- This is one of 3 issues she let me know were already sized and that would be worked in this sprint.
- Moving them to the right columns in the backlog and sprint board.
