### ISSUE TITLE
Publish Dataset: Show new version numbers in Publish Popup

### ISSUE THREAD

**Issue by ekraffmiller** [IQSS/dataverse-frontend#428]
In the JSF publish form, if the dataset was previously published, the form displays the new version numbers for the major and minor version updates, for example:
<img width="979" alt="Screenshot 2024-07-02 at 7 09 55 PM" src="https://github.com/IQSS/dataverse-frontend/assets/675224/4f3200bf-8c56-4813-8225-3de654a67b76">

In the SPA, we need the version number of the most recently published version, in order to derive the new version numbers.  This may require changes to js-dataverse and the dataverse API for the Get Dataset use case.

**Comment by GermanSaracca** [comment]
I add waiting tag because it depends first of all on the completion of [#176](https://github.com/IQSS/dataverse-client-javascript/issues/176) and [#10761](https://github.com/IQSS/dataverse/issues/10761)

**Comment by ekraffmiller** [comment]
After discussing the options in https://github.com/IQSS/dataverse/issues/10761, it was decided to make a second call to the API to get the :latest-published version of the dataset, rather than update the existing API.  So, we are no longer waiting for https://github.com/IQSS/dataverse/issues/10761 and https://github.com/IQSS/dataverse-client-javascript/issues/176
