### ISSUE TITLE
prefill name for Author and Point of Contact should be "FamilyName, GivenName" format

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse-frontend#436]
**What steps does it take to reproduce the issue?**

Click "create dataset"

- When does this issue occur?

Always

- Which page(s) does it occur on?

Create dataset page

- What happens?

Author Name and Point of Contact Name are pre-populated with "Philip Durbin" (for example) instead of "Durbin, Philip".

- To whom does it occur (all users, curators, superusers)?

All users.

- What did you expect to happen?

It should be "Durbin, Philip" like the watermark says: "1) FamilyName, GivenName or 2) Organization"

**Which version of Dataverse Frontend are you using?**

91b2db6

**Any related open or closed issues to this bug report?**

- #414

**Screenshots:**

![Screenshot 2024-07-18 at 11 21 51 AM](https://github.com/user-attachments/assets/055e3ef9-a948-4973-9ed3-a93a0045edd0)

**Comment by jggautier** [comment]
Hi @pdurbin  and @ChengShi-1. The notification about the PR at https://github.com/IQSS/dataverse-frontend/pull/490 and work on these metadata fields made me just notice this GitHub issue.

Is the new frontend already filling the Depositor field with the depositor's name in the way we expect, too (like the current version of Dataverse is)?

**Comment by ChengShi-1** [comment]
> Hi @pdurbin and @ChengShi-1. The notification about the PR at #490 and work on these metadata fields made me just notice this GitHub issue.
> 
> Is the new frontend already filling the Depositor field with the depositor's name in the way we expect, too (like the current version of Dataverse is)?

There is no pre-fill in Depositor field currently, we should add it too.
