### ISSUE TITLE
[Spike - Analysis] Edit Dataset Metadata: string field values contain markdown

### ISSUE THREAD

**Issue by ekraffmiller** [IQSS/dataverse-frontend#499]
**What steps does it take to reproduce the issue?**

Create a Dataset with a description that contains html markup, for example `<b>test</b>`.
View the Dataset and see that the description is displayed as **test** (correctly displayed as bold).
Choose Edit Metadata.
In the EditMetadata form, the description is shown as Markdown instead of html, for example `**test**`.
If the Dataset is saved again, the description test is converted again the Markdown, so it appears as `**test**`, rather than **test**.

- When does this issue occur?
Editing Dataset Metadata that contains html markup

- Which page(s) does it occur on?
Edit Dataset Metadata

- What happens?
Metadata field value is displayed with Markdown rather than html

- To whom does it occur (all users, curators, superusers)?
all users

- What did you expect to happen?
The metadata value should be displayed with the html markup that is returned by the Dataverse API

**Note**: This will probably require a change to js-dataverse also, either to stop converting the html to markdown get Get Dataset use case, or have that conversion happen optionally.  

**Any related open or closed issues to this bug report?**

**Screenshots:**

https://github.com/user-attachments/assets/c0be90ed-8c9c-4841-bc98-d1326acadf94

**Comment by g-saracca** [comment]
I would be inclined to avoid **_html to markdown_** transformations in js-dataverse.
This way the information is not modified and the js-dataverse consumer can handle the field as desired.
Saying that, I would love to make a special component similar to how Github handles comments, where the user can write both markup and html and can see the preview of it.
Then, from the SPA, before sending the markup collected by the component to the js-dataverse use case, this markup would be transformed back to html, so we only send html from the SPA at the end.
Then for the case of editing a dataset, when receiving the html from the use case, a transformation from html to markdown would have to be done inside the SPA to fill the form field.

I have some doubts:
- Dataverse backend would or is supporting all kind of html tags that could be generated from a markdown? 
- Another point would be to know when a metadata field can be filled with html, to know when to render this custom "rich text editor component", maybe all metadata fields of type “TEXTBOX”?

**Comment by g-saracca** [comment]
A parameter will be added to the js-dataverse use case that returns a dataset, to configure whether you want the metadata fields as markdown or as raw only.
