### ISSUE TITLE
Define and establish the Dataverse frontend QA process

### ISSUE THREAD

**Issue by GPortas** [IQSS/dataverse-frontend#5]
## Overview of the Feature Request

In order to manage frontend issues within a workflow similar to the one we follow for the main Dataverse repository, it is necessary to define an appropriate QA process that suits the needs of a React SPA, which may differ from those of the Dataverse backend.

The goal is to define a QA process guideline that allows the Dataverse QA team to perform the appropriate actions on the Dataverse frontend, before merging any PR.

## What kind of user is the feature intended for?
Dataverse frontend developers and QA

## What inspired the request?
- Current opened PR #4 
- Discussion with @pdurbin, @mreekie and @kcondon

## What existing behavior do you want changed?
N/A

## Any brand new behavior do you want to add to Dataverse Frontend?
N/A

## Any related open or closed issues to this feature request?

- #1 
- #2 
- #3

**Comment by pdurbin** [comment]
@kcondon @GPortas thanks for the call about this. Here's the doc we started: https://docs.google.com/document/d/1xSfwU2kQJdLdr2XKy8jUH5MBTO4NsiF8etzSs5k4A_w/edit?usp=sharing
