### ISSUE TITLE
API Token section - Read current API Token integration

### ISSUE THREAD

**Issue by g-saracca** [IQSS/dataverse-frontend#506]
**Overview of the Feature Request**
Integrate the read current api token use case to display the api token.
This will be the initial work of [API Token use cases integration issue](https://github.com/IQSS/dataverse-frontend/issues/505).

**Any open or closed issues related to this feature request?**

1. [Recreate API Token integration](https://github.com/IQSS/dataverse-frontend/issues/507)
2. [Revoke API Token integration](https://github.com/IQSS/dataverse-frontend/issues/508)

**Depends on:**

- https://github.com/IQSS/dataverse/pull/10924

**Comment by GPortas** [comment]
https://github.com/IQSS/dataverse/issues/10914 should unblock this issue
