### ISSUE TITLE
API Token section - Recreate API Token integration

### ISSUE THREAD

**Issue by g-saracca** [IQSS/dataverse-frontend#507]
**Overview of the Feature Request**
Integrate the recreate api token to create a new token and also te recreate an existing one.

This issue is part of the [API Token section use cases integration](https://github.com/IQSS/dataverse-frontend/issues/505) issue.

**Any open or closed issues related to this feature request?**

Waiting tag has been added because it depends first on the completion of [Read current API Token integration](https://github.com/IQSS/dataverse-frontend/issues/506)

**Comment by ChengShi-1** [comment]
This issue will be included into #506
