### ISSUE TITLE
API Token section - Revoke API Token integration

### ISSUE THREAD

**Issue by g-saracca** [IQSS/dataverse-frontend#508]
**Overview of the Feature Request**
Integrate the revoke api token use case to delete the current api token.

This issue is part of the [API Token section use cases integration](https://github.com/IQSS/dataverse-frontend/issues/505) issue.

**Any open or closed issues related to this feature request?**

Waiting tag has been added because it depends first on the completion of [Read current API Token integration](https://github.com/IQSS/dataverse-frontend/issues/506)n

**Comment by ChengShi-1** [comment]
This issue will be included into #506
