### ISSUE TITLE
More personalizable collections - Analysis

### ISSUE THREAD

**Issue by g-saracca** [IQSS/dataverse-frontend#514]
**Overview of the Feature Request**

This is to analyze point 3 of the [Epic: Design, demonstrate, and implement new SPA-based Dataverse homepage and collection pages](https://github.com/IQSS/dataverse-pm/issues/231)

**What kind of user is the feature intended for?**
SPA Users

**What inspired the request?**
Q4 Roadmap

**Comment by g-saracca** [comment]
@sekmiller @scolapasta @siacus @jggautier @GPortas 
I have created a possible design to add another way to personalize collections, I call them "**_featured items_**".

The idea is to be able to create featured items for a collection from [this page](https://646f68aa9beb01b35c599acd-mkocrfmooq.chromatic.com/?path=/story/pages-collection-featured-items--default) - (This is from Storybook so its working with mocked data).
An MVP for this first iteration of this feature offers users the ability to add, remove and sort by drag-and-drop these featured items, and also preview them in real time as they are being added, modified, sorted or deleted.
These featured items will have a **_title_** and **_text content_** or **_text  content + image_**.
The idea is that in future iterations we will make a rich text editor to enrich the content.
_*Note: the design for mobile screens and image uploading has not been developed to first get an idea that we are on the right track._

And then, if a collection has featured items, they will be displayed like in [this Storybook](https://646f68aa9beb01b35c599acd-mkocrfmooq.chromatic.com/?path=/story/pages-collection--with-featured-items).

One idea would be that if a collection contains a description and featured items, the description would be displayed as the first item in the featured items carousel, titled as “About”.
Also for a future iterations it could be a good idea to create from this same section, featured collections and featured datasets to display in the carousel.

This is an end to end feature, meaning it will require work on the backend, api and frontend:

- API endpoint to create/modify the featured items.
- API endpoint to get the featured items of an specific collection.
- JS-dataverse use case to to create/modify the featured items.
- JS-dataverse to get the featured items of an specific collection.
- SPA Frontend integration with the use cases.

As a first instance I would like to know what you think so we can plan the remaining work. Many thanks!

**Comment by sekmiller** [comment]
The idea that I was trying to describe in today's meeting was it would be great if a featured item could be a dvobject (collection, dataset, or file) from the installation - either owned by the collection that is featuring it or from outside the current collection.  Either way, adding a link so that the end user could go directly to that featured item. Probably not needed for the first iteration, but something that you could be mindful of for the future.

**Comment by g-saracca** [comment]
@sekmiller  Yes, I think that's great, a similar idea was suggested by the rest of the SPA frontend team when I showed them this proposal.
I think we could have a different structure for this kind of dvobjects items, both for how the carousel cards will look like and how the information about each featured item will be sent and retrieve from and to the API.

Maybe we could handle this type of data model, these are the Typescript types I have in mind:

```
type FeaturedItem = CustomFeaturedItem | DvObjectFeaturedItem

type CustomFeaturedItem = {
  type: 'custom'
  title: string
  content: string
  image?: {
    url: string
    altText: string
  }
}

type DvObjectFeaturedItem = {
  type: DvObjectType // 'collection' | 'dataset' | 'file'
  linkUrl: string
  title: string
  description?: string
}
```

**Comment by jggautier** [comment]
Hi @g-saracca. This is cool. Thanks for sharing.

Do you think it would be helpful at this point to also seek feedback from folks who've created collections? I could help with that, or at least help with starting to think about that.

I'm also thinking about how exactly these changes might be evaluated, and looking at the related GitHub issue at https://github.com/IQSS/dataverse-pm/issues/231 for more info. @cmbz wrote that "Feature analysis for item 3 and 4 is underway" and pointed to this GitHub issue.

So at the moment this design is meant to satisfy the goals of tasks 3 and 4?

Not very related, but I'm excited to see some new design patterns (new to Dataverse!) that could be useful in other parts of Dataverse, too, like the dataset metadata form. Some inspiration for the Citation metadata block redesign that the UX working group has been working on.

**Comment by g-saracca** [comment]
Hi @jggautier, thanks to you.

This is to satisfy only task 3 from the [Epic #231](https://github.com/IQSS/dataverse-pm/issues/231). The idea is to have the MVP of this feature working by this last quarter of the year.

Regarding feedback, it would be great to hear some comments on this so we can fine tune this or see if we are not missing something, even not only for this first iteration but for future iterations as well.

> Not very related, but I'm excited to see some new design patterns (new to Dataverse!) that could be useful in other parts of Dataverse, too, like the dataset metadata form. 

Yeah, maybe not the place here but we have this [open SPA issue - 438](https://github.com/IQSS/dataverse-frontend/issues/438) for example, the drag-and-drop functionality from this feature could be implemented also to accomplish the requirement in 438 🙌 .

**Comment by siacus** [comment]
This is nice German, I think we can start simple and grow. A couple of ideas: 1) let the user decide if they want a carousel or just an image; 2) let the user decide if dataset can be shown after pushing the button 'show me data" or always; 3) what about the idea of a background color/pattern or image with transparency (i.e. the content is always visible, the image/bakcground is rendered with transparency)? And make it part of a "theme" element (for the future).

**Comment by g-saracca** [comment]
Hi @siacus, thanks for the feedback!

**_Point 2_** seems to me a great idea and we can easily achieve it with a checkbox/toggle to allow the user to enable or disable that.

About **_point 1_**, I don't fully understand, if we go for just an image then the user will not be able to add more than one feature item? The carousel is to be able to navigate through the different items, what we could do is in the case that there is only one item configured _(either with image or image + text)_ simply show the item  without the carousel indicators and arrows.

Regarding point 3, what you are referring to is a background with transparency under each featured item? 
Or maybe you are talking about a kind of cover behind the collection page header?

**Comment by siacus** [comment]
on point 1: ok, it seems what I am asking coincides with the case with only one feature

point 3: I mean something in gmail background (see screenshot): 

<img width="1491" alt="image" src="https://github.com/user-attachments/assets/147f2acf-e7dd-4bd3-9cb9-59ce19c67e65">

**Comment by g-saracca** [comment]
Oh yes! I love that idea and I have several proposals about it too! 
I think it will be a good idea to tackle that when the time comes to replicate the Theme & Widgets section of the current JSF version.

**Comment by g-saracca** [comment]
Issues were created to start with API work and also JS-Dataverse use cases

- https://github.com/IQSS/dataverse/issues/10943
- https://github.com/IQSS/dataverse-client-javascript/issues/202
