### ISSUE TITLE
Replace the hard-coded wait with the pipe() method

### ISSUE THREAD

**Issue by ChengShi-1** [IQSS/dataverse-frontend#534]
**Overview of the Feature Request**
Inspired from existing TODO, [In the Dataset.spec.tsx](https://github.com/IQSS/dataverse-frontend/blob/82e4779703c5abe4c5df5165b256a84da040aa61/tests/e2e-integration/e2e/sections/dataset/Dataset.spec.tsx#L441) of the e2e test, we have the cy.wait(500), could be replaced by the pipe() method. [Reference here.](https://www.cypress.io/blog/when-can-the-test-click)

Since pipe() is not a native feature of Cypress, a community plugin called `cypress-pipe` should be installed and added.

**Comment by g-saracca** [comment]
I think for the moment we don't need it as the test works perfectly with the existing "wait" and it is not convenient to add an extra dependency to maintain (pipe is not included in cypress), the dependency to achieve this is called [cypress-pipe](https://www.npmjs.com/package/cypress-pipe), it uses some deprecated cypress methods and is currently not maintained so I would prefer to avoid this change and close this issue.

@ChengShi-1 , @ekraffmiller what do you think?
