### ISSUE TITLE
Feature Request/Idea:

### ISSUE THREAD

**Issue by kuhlaid** [IQSS/dataverse-frontend#552]
**What kind of user is the feature intended for?**
Everyone

**What inspired the request?**
Trying to filter a dataset but keep getting redirected to the top of the page and needing to scroll back down to the files.

**What existing behavior do you want changed?**
When a file filter is applied, for example if a user selects a different file type, file tag or even the file sorting option, this refreshes the page with the filtered content. The problem is that it sends the user back to the top of the page and thus loses focus on the file list, so the user if forced to scroll back down to the bottom of the page where the files are located. Ideally the file list would retain focus when filters selections changed by a user.

**Any brand new behavior do you want to add to Dataverse?**
One option would be to add an anchor tag at the dataset 'tabs' (Files, Metadata, Terms, Version) and when a filter is applied, the URL will include the anchor so that the page refresh keeps the files in focus (see screenshot below of the dataset tabs I am referring to). If the file list can be refreshed without redrawing the entire HTML page that would work as well but it depends on how you are choosing to handle content changes on a page.

![image](https://github.com/IQSS/dataverse/assets/41551429/ff91ef6c-f164-410f-a319-153c0d21e4b7)

If you are on the dataset page under Table View and you choose a different File Tag (on page https://beta.dataverse.org/dataset.xhtml?persistentId=doi%3A10.5072%2FFK2%2FK8E7PV&version=&q=&fileTypeGroupFacet=%22Tabular+Data%22&fileAccess=&fileTag=%22Data%22&fileSortField=&fileSortOrder=&tagPresort=true&folderPresort=true for example), the page refreshes and takes you back to the top of the page. Maybe simply use anchor tags in the URL (e.g. #tabs to pull the focus back down to the tabbed section). Thank you.

(This issue was originally submitted under https://github.com/IQSS/dataverse/issues/9917.)

**Comment by pdurbin** [comment]
@kuhlaid sorry, sorry, I only just noticed the "xhtml" in the URL you tried. It's confusing. The beta server has both the old UI (JSF) and the new UI (React) on it.

Can you you please try again at https://beta.dataverse.org/spa ? To see if you can reproduce this in the React app, I mean.

**Comment by kuhlaid** [comment]
Hi @pdurbin, the SPA does not work. If I visit https://beta.dataverse.org/spa/collections it says page cannot be found. If I try the search function, same thing. Login same thing...

**Comment by kuhlaid** [comment]
Hi @g-saracca , yes the SPA version seems to hold the page in place (which is ideal).

**Comment by g-saracca** [comment]
Thanks for confirming @kuhlaid , @pdurbin  should we close this issue in this repo?

**Comment by pdurbin** [comment]
Yeah, I'll go ahead and close it. Thanks, all!
