### ISSUE TITLE
Create the citation block of the Dataset

### ISSUE THREAD

**Issue by GPortas** [IQSS/dataverse-frontend#59]
## Overview of the Feature Request

The goal is to create the citation block of the Dataset page.

The original block contains a dropdown menu called "Cite Dataset". We are going to ignore that in this first iteration.

### Mockup of the requested element

![citation_block_isolate_v2](https://user-images.githubusercontent.com/17010447/233393677-1e17dc10-8b0f-4bf7-ad63-f298f28a0eb2.png)

![citation_block_inpage_v3](https://user-images.githubusercontent.com/17010447/233393696-b00b19dc-fd0f-4bc5-a573-1774adb13c5a.png)

### Process action items

_Find out more about the action items in the [process definition](https://docs.google.com/document/d/1vOSsIGGCbgal4f_lSp1yInQifBcmo5vZ-Z9pfkVDyG4/edit#heading=h.e6y69fx5m61r)_

- [ ] Analyze required data access logic
- [ ] Document associated API endpoints
- [ ] Develop the UI element
- [ ] Add the element to the page and storybook
- [ ] Create spike issues if required and add them to _related open or closed issues_

## What inspired the request?

- UI discussion on Dataset page initial work

## What existing behavior do you want changed?

N/A

## Any brand new behavior do you want to add to Dataverse?

- Citation block in the Dataset page

## Any open or closed issues related to this feature request?

- https://github.com/IQSS/dataverse-frontend/issues/72
- https://github.com/IQSS/dataverse-frontend/issues/82
- https://github.com/IQSS/dataverse-frontend/issues/89

**Comment by pdurbin** [comment]
Please note that there should be a tooltip (screenshot below) when the dataset is in draft:

<img width="542" alt="Screen Shot 2023-04-25 at 11 50 48 AM" src="https://user-images.githubusercontent.com/21006/234333226-340202f8-04ae-476f-9ccd-30013cc08368.png">
