### ISSUE TITLE
Setup local development environment for Dataverse backend

### ISSUE THREAD

**Issue by GPortas** [IQSS/dataverse-frontend#65]
## Overview of the Feature Request

The goal is to establish an automated mechanism to initialize a Dataverse instance, with all its dependencies, locally, for frontend development purposes.

It is important that the Dataverse instance is configured with the session authentication feature flag enabled to allow session cookie authentication.

We can build the solution from the current container-based development mechanism based on docker-compose, present in the core repository, and adapt it to the needs of the frontend.

**EDIT: it will be necessary to create a proxy on top of SPA and Dataverse to avoid CORS issues.**

## What kind of user is the feature intended for?

- Frontend developers

## What inspired the request?

- #53 

## What existing behavior do you want changed?

No

## Any brand new behavior do you want to add to Dataverse?

Add a local dev environment for Dataverse

## Any open or closed issues related to this feature request?

- https://github.com/IQSS/dataverse/issues/9423

**Comment by pdurbin** [comment]
We could use the "sample data" repo to create some datasets within the test environment: https://github.com/IQSS/dataverse-sample-data

Once upon a time @poikilotherm even worked a bit on Dockerizing it:

- https://github.com/IQSS/dataverse-sample-data/pull/14

**Comment by poikilotherm** [comment]
Let me add that IQSS#9444 is no longer a draft. Hopefully this is useful for this issue.
