### ISSUE TITLE
Layout component

### ISSUE THREAD

**Issue by MellyGray** [IQSS/dataverse-frontend#7]
## Overview of the Feature Request

To start developing some pages for the SPA MVP we are going to need a common Layout component for all the pages. This Layout component is a wrapper with the common elements to all the pages, such as the header and the footer. All the pages will extend this component as a children.

## What kind of user is the feature intended for?
Dataverse frontend developers

## What inspired the request?
- Current work on SPA MVP Strategy
- MVP Strategy document: [link](https://docs.google.com/document/d/1vOSsIGGCbgal4f_lSp1yInQifBcmo5vZ-Z9pfkVDyG4)

## What existing behavior do you want changed?
The example page HelloDataverse.tsx will be encapsulated in the Layout component to serve as a real example.

## Any brand new behavior do you want to add to Dataverse Frontend?

-  Layout component wrapper for the future Dataverse pages.
-  Header component
-  Footer component
-  Add those components to the Storybook

## Any related open or closed issues to this feature request?

Storybook need to be set up https://github.com/IQSS/dataverse-frontend/issues/3

**Comment by mreekie** [comment]
Grooming:
- Added NIH deliverable label.
