### ISSUE TITLE
[Spike - Frontend] Create the boilerplate of the Dataset section with Dataset title

### ISSUE THREAD

**Issue by GPortas** [IQSS/dataverse-frontend#78]
## Overview of the Feature Request

Implement the UI for #58 .

## What kind of user is the feature intended for?

Developers

## What inspired the request?

- [UI feature development process](https://docs.google.com/document/d/1vOSsIGGCbgal4f_lSp1yInQifBcmo5vZ-Z9pfkVDyG4/edit#heading=h.e6y69fx5m61r)

## What existing behavior do you want changed?

N/A

## Any brand new behavior do you want to add to Dataverse?

N/A

## Any open or closed issues related to this feature request?

- #58.

**Comment by pdurbin** [comment]
As I mentioned during the meeting just now, as has been discussed elsewhere...

- https://github.com/IQSS/dataverse/issues/2110

... it's not super fun to get a dataset title from the native API. Here's how:

`curl -s https://dataverse.harvard.edu/api/datasets/:persistentId/?persistentId=doi:10.7910/DVN/TJCLKP | jq '.data.latestVersion.metadataBlocks.citation.fields[] | select(.typeName=="title").value' -r`

```
Open Source at Harvard
```

As discussed, this is why @JR-1991 created [EasyDataverse](https://github.com/gdcc/easyDataverse). 😄 

Oh and not as bad but to get the version (e.g. 4.0), you need to concatenate major and minor:

`curl -s https://dataverse.harvard.edu/api/datasets/:persistentId/?persistentId=doi:10.7910/DVN/TJCLKP | jq '.data.latestVersion.versionNumber'`

```
4
```

`curl -s https://dataverse.harvard.edu/api/datasets/:persistentId/?persistentId=doi:10.7910/DVN/TJCLKP | jq '.data.latestVersion.versionMinorNumber'`

```
0
````

Again, I think we should at some point take a look at the [Semantic API](https://guides.dataverse.org/en/5.13/developers/dataset-semantic-metadata-api.html) @qqmyers created, though as I said I believe you need an API token to get even published datasets. It's probably a little friendlier. For now, starting with the native JSON API is fine.
