### ISSUE TITLE
Configure e2e test environment for GitHub actions

### ISSUE THREAD

**Issue by GPortas** [IQSS/dataverse-frontend#92]
## Overview of the Feature Request

Currently the e2e tests are temporarily disabled on GitHub actions (the corresponding GitHub action job is commented out), since they need a running dedicated Dataverse instance to work.

The goal is to set up a suitable environment for e2e tests to work on the GitHub action and enable the job to run again.

## What inspired the request?
- Disabling e2e action job on #67 

## What kind of user is the feature intended for?
Developers and testers

## What existing behavior do you want changed?
N/A

## Any brand new behavior do you want to add to Dataverse?
N/A

## Any open or closed issues related to this feature request?
- #67

**Comment by kcondon** [comment]
@GPortas Thanks!
